services:
    pix_sortable_behavior.position.orm:
        class: Pix\SortableBehaviorBundle\Services\PositionORMHandler
        public: false
        arguments:
            - "@doctrine.orm.entity_manager"
        calls:
            - [ 'setPositionField', ["%pix.sortable.behavior.position.field%"]]
            - [ 'setSortableGroups', ["%pix.sortable.behavior.sortable_groups%"]]

    pix_sortable_behavior.position.mongodb:
        class: Pix\SortableBehaviorBundle\Services\PositionODMHandler
        public: false
        arguments:
            - "@doctrine_mongodb.odm.document_manager"
        calls:
            - [ 'setPositionField', ["%pix.sortable.behavior.position.field%"]]

    pix_sortable_behavior.twig.extension:
        class: Pix\SortableBehaviorBundle\Twig\ObjectPositionExtension
        arguments:
            - "@pix_sortable_behavior.position"
        public: false
        tags:
            - { name: twig.extension }
